# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_constructors_over_static_methods: false
