name: whiskit
description: This App for Whisky Lover
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^1.0.3
  firebase_analytics: ^8.0.0-dev.0
  firebase_core: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
