name: whiskit
description: This App for Whisky Lover
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  cloud_firestore: ^1.0.3
  cloud_firestore_platform_interface: ^4.0.1
  enum_to_string: ^2.0.1
  firebase_analytics: ^8.0.0-dev.0
  firebase_auth: ^1.0.2
  firebase_core: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+1
  flutter_signin_button: ^2.0.0
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.1
  google_sign_in_web: ^0.10.0+1
  pedantic: ^1.11.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
